name: Feature branch workflow

on:
  push:
    branches:
      - feature/*

jobs:
  mybuild:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
        
      - name: print Java version
        run: echo 'java -version'

      - name: maven build
        run: mvn clean install
