name: Feature branch workflow

on:
  push:
    branches:
      - feature/*

jobs:
  mybuild:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: print Java version
        run: echo `java -version`

      - name: print Maven version
        run: echo `mvn -version`

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 1.8

      - name: maven build
        run: mvn clean install
