name: Feature branch workflow

on:
  push:
    branches:
      - feature/*

jobs:
  codebuild:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: print Java version
        run: echo `java -version`

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: print Maven version
        run: echo `mvn -version`

      - name: maven build
        run: mvn clean install

      - name: print Docker version
        run: echo `docker --version`

      - name: docker build
      - run: docker build --build-arg JAR_FILE=build/libs/\*.jar -t manngnit/testdevops .