name: Feature branch workflow

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: print Java version
        run: echo `java -version`

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: print Maven version
        run: echo `mvn -version`

      - name: maven build
        run: mvn clean install

      - name: docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: manngnit/testdevops:1.0