name: Feature branch workflow

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK to version 8
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '8'
          distribution: 'alpine'

      - name: Print Java version
        run: echo `java -version`

      - name: Maven build
        run: mvn clean verify